name: Run tests
on: [push, pull_request]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    container: 
      image: stelar7/advent-of-code-runner:2022
    env:
      PASSED_TESTS: 0

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run tests
        shell: bash
        run: |
          make test YEAR=2023 DAY=1;
          make test YEAR=2023 DAY=2;
          make test YEAR=2023 DAY=3;
          make test YEAR=2023 DAY=4;
          make test YEAR=2023 DAY=5;
          make test YEAR=2023 DAY=6;
          make test YEAR=2023 DAY=7;
          make test YEAR=2023 DAY=8;
          make test YEAR=2023 DAY=9;
          make test YEAR=2023 DAY=10;
          make test YEAR=2023 DAY=11;
          make test YEAR=2023 DAY=12;
          make test YEAR=2023 DAY=13;
          make test YEAR=2023 DAY=14;
          make test YEAR=2023 DAY=15;
          make test YEAR=2023 DAY=16;
          make test YEAR=2023 DAY=17;
          make test YEAR=2023 DAY=18;
          make test YEAR=2023 DAY=19;
          make test YEAR=2023 DAY=20;
          make test YEAR=2023 DAY=21;
          make test YEAR=2023 DAY=22;
          make test YEAR=2023 DAY=23;
          make test YEAR=2023 DAY=24;
          make test YEAR=2023 DAY=25;

      - name: Check for failed tests
        run: |
          ! grep -r "❌" leaderboards/*
          echo "PASSED_TESTS=$?" >> "$GITHUB_ENV"
          exit $PASSED_TESTS

      - name: Output logs
        if: always() && env.PASSED_TESTS == 1
        run: |
          find logs/ -type f -name *.log -print -exec cat {} \;

      - name: Push new leaderboards
        if: always() && github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add leaderboards/*
          git commit -m "Update leaderboards"
          git push
